IdentityServer/Views/Shared/Components/GigyaLogin/GigyaLoginViewComponent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using Microsoft.AspNetCore.Html;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ViewFeatures;
using Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http;
using Microsoft.Extensions.Hosting;


namespace Gigya.Razor.Components
{
    [ViewComponent(Name = "GigyaLogin")]
    public class GigyaLoginViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync(string screenSet = "Default-RegistrationLogin",
            string startScreen = "gigya-login-screen", string onSubmitUrl = null)
        {
            
            return View("Default", new GigyaScreen(screenSet, startScreen, onSubmitUrl));
        }
    }

    public static class GigyaExtensions
    {
        public static IHtmlContent SdkScript(this ViewDataDictionary viewData) => new HtmlString(
            $"<script async src='https://cdns.{viewData["gigya.domain"]}/js/gigya.js?apikey={viewData["gigya.apiKey"]}'></script>");
 
        
        public static Request Request(
            this ViewDataDictionary viewData,
            string api )
        {
            if (viewData == null)
            {
                throw new ArgumentNullException(nameof(viewData));
            }
 
            var site = viewData.Site();
            return site.Request(new Request(api));

        }
        // public static string GigyaGetRequest(
        //     this IUrlHelper helper,
        //     string api = null,
        //     string @namespace = null,
        //     object values = null,
        //     string protocol = null,
        //     string host = null,
        //     string fragment = null)
        // {
        //     if (helper == null)
        //     {
        //         throw new ArgumentNullException(nameof(helper));
        //     }
        //
        //     var httpContext = helper.ActionContext.HttpContext;
        //
        //     protocol ??= httpContext.Request.Scheme;
        //
        //     var site = helper.ActionContext.Site();
        //     return site.Request(new Request(api), protocol).Uri().ToString();
        //    
        // }
        //
        public static GigyaSite Site(this ActionContext context) => new GigyaSite(context);
        public static GigyaSite Site(this ViewDataDictionary context) => new GigyaSite(context);

 
    }
    
           public record Request(string Api = "gs/ver.htm", Dictionary<string, string> Params = null,
            string Host = "accounts.gigya.com")
        {
            public Dictionary<string, string> Params { get; init; } = Params ?? new Dictionary<string, string>();
            public string Scheme = HttpScheme.Https.ToString();

            public (string name, string value) Param
            {
                init => Params[value.name] = value.value;
            }

            public HttpGetRequest Get() => new(this);

            // public IEnumerable<(string name, string value)> SetParams
            // {
            //     init { _ = value.ForEach(param => Params[param.name] = param.value); }
            // }
        };

         

        public record HttpGetRequest(Request Request) : Request(Request)
        {
            public Uri Uri()
            {
                return new UriBuilder()
                {
                    Scheme = Scheme,
                    Host = Host,
                    Path = Request.Api,
                    Query = Query()
                }.Uri;
            }

            private string Query() =>
                Request
                    .Params
                    .Select(tuple => $"{HttpUtility.UrlEncode(tuple.Key)}={HttpUtility.UrlEncode(tuple.Value)}")
                    .Aggregate("?", (query, param) => $"{query}{param}&")
                    .TrimEnd('&');
        };

        public class GigyaSite
        {
            public string ApiKey { get; set; }
            public string Domain { get; set; } = "gigya.com";

            public GigyaSite(ActionContext context)
            {
                if (context.ModelState.TryGetValue("gigya.domain", out var stateEntry) &&
                    stateEntry.RawValue is string domain)
                {
                    Domain = domain;
                }

                if (context.ModelState.TryGetValue("gigya.apiKey", out var stateApiKey) &&
                    stateApiKey.RawValue is string apiKey)
                {
                    ApiKey = "gigya.com";
                }
            }

            public GigyaSite(ViewDataDictionary viewDataDictionary)
            {
                ApiKey = viewDataDictionary["gigya.apiKey"] as string;
                Domain =  viewDataDictionary["gigya.domain"]as string;
            }
 
            public Request Request(Request request,
                string @namespace = "accounts",
                string host = null,
                string fragment = null)
            {
                return request with { Param = ("apiKey", ApiKey), Host = domain() } ;

                string domain() => host ?? $"{@namespace}.{Domain}";
            }
            public HttpGetRequest GetRequest(Request request,
                string @namespace = "accounts",
                string host = null,
                string fragment = null)
            {
                return new HttpGetRequest(request with { Param = ("apiKey", ApiKey), Host = domain() });

                string domain() => host ?? $"{@namespace}.{Domain}";
            }
        }
}

IdentityServer/Views/Shared/Components/GigyaScreen/GigyaScreenViewComponent.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;


namespace  Gigya.Razor.Components
{
    [ViewComponent(Name = "GigyaScreen")]

    public class GigyaScreenViewComponent : ViewComponent
    {    
        public async Task<IViewComponentResult> InvokeAsync(string screenSet, string startScreen = null ,string onSubmitUrl = null)
        {
            return View("Default", new GigyaScreen(screenSet, startScreen, onSubmitUrl));
        }
    }
 

    public class GigyaScreen
    {
        public string ScreenSet;
        public string StartScreen;
        public string OnSubmitUrl;

        public GigyaScreen(string screenSet, string startScreen, string onSubmitUrl)
        {
            ScreenSet = screenSet;
            StartScreen = startScreen;
            OnSubmitUrl = onSubmitUrl;
        }

        public string ReturnUrl { get; set; }
    }
}

IdentityServer/Views/Shared/Components/GigyaStore/GigyaViewComponent.cs
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Html;
using Microsoft.AspNetCore.Mvc;

namespace Gigya.Razor.Components
{
    public class GigyaStoreViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync(string apiKey, string domain)
        {
            return View("Default", new GigyaStore(apiKey , domain ));
        }
    }

    // public class GigyaStoreTag: TagHelper
    // {
    //     public readonly string ApiKey;
    //     public readonly string Domain;
    //     public readonly IEnumerable<ViewComponent> Children;
    //
    //     public GigyaStoreTag(string apiKey, string domain = "gigya.com")
    //     {
    //         ApiKey = apiKey;
    //         Domain = domain;
    //     }
    //
    //     public override Task ProcessAsync(TagHelperContext context, TagHelperOutput output)
    //     {
    //         output.TagName = "script";    // Replaces <email> with <a> tag
    //         // output.PreContent =
    //         //     $"<script async src='https://cdns.{Domain}/js/gigya.js?apikey={ApiKey}></script>";
    //         //
    //         //
    //         // var address = MailTo + "@" + EmailDomain;
    //         output.Attributes.SetAttribute("src",  $"<script async src='https://cdns.{Domain}/js/gigya.js?apikey={ApiKey}></script>");
    //         // output.Content.SetContent(   );
    //
    //         return base.ProcessAsync(context, output);
    //     }
    //
    //     public IHtmlContent SdkScript()
    //     {
    //         return new HtmlString($"<script async src='https://cdns.{Domain}/js/gigya.js?apikey={ApiKey}'></script>");
    //     }
    // }
    public class GigyaStore
    {
        public readonly string Content;
        public readonly string ApiKey;
        public readonly string Domain;
        public readonly IEnumerable<ViewComponent> Children;

        public GigyaStore(string apiKey, string domain = "gigya.com", string? content = null)
        {
            Content = content;
            ApiKey = apiKey;
            Domain = domain;
        }

        public IHtmlContent SdkScript()
        {
            return new HtmlString($"<script async src='https://cdns.{Domain}/js/gigya.js?apikey={ApiKey}'></script>");
        }
    }
}

IdentityServer/Views/Shared/Components/JwtDebug/JwtDebugViewComponent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Security.Claims;
using System.Threading.Tasks;
using System.Web;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Html;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ViewFeatures;
using Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http;
using Microsoft.Extensions.Hosting;


namespace Gigya.Razor.Components
{
    [ViewComponent(Name = "JwtDebug")]
    public class JwtDebugViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync()
        {

            return View("Default" );
        }
    }

    
}

IdentityServer/Views/Shared/Components/LoginStatus/LoginStatusViewComponent.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace Gigya.Razor.Components 
{
    public class LoginStatusViewComponent : ViewComponent
    {
        // private readonly SignInManager<GigyaUser> _signInManager;
        // private readonly UserManager<GigyaUser> _userManager;
        //
        // public LoginStatusViewComponent(SignInManager<GigyaUser> signInManager, UserManager<GigyaUser> userManager)
        // {
        //     _signInManager = signInManager;
        //     _userManager = userManager;
        // }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var authontication = await HttpContext.AuthenticateAsync();
            if (authontication.Succeeded)
            {
                return View("LoggedIn", authontication);
            }
            else
            {
                return View("Login");
            }
        }
    }
}

IdentityServer/Views/Shared/Components/JwtDebug/Default.cshtml
@using Microsoft.AspNetCore.Authentication
@inject IAuthenticationService AuthenticationService
@{
    var containerID = "gigya-screen-container";
    var user = await AuthenticationService.AuthenticateAsync(Context, "Gigya-JWT");

}
@ViewData.SdkScript();
 @* <vc:gigya-store domain="@ViewData["gigya.domain"]" api-key="@ViewData["gigya.apiKey"]"></vc:gigya-store> *@
 <div id="@containerID" style="flex: max-content; height: 600; width: auto"></div>
@ViewData.Request("accounts.getJWT").Get().Uri().ToString()
 @if (user?.Principal?.Claims != null)
 {
     <div class="diagnostics-page">
         <div class="lead">
             <h1>Authentication Cookie</h1>
         </div>

         <div class="row">
             <div class="col">
                 <div class="card">
                     <div class="card-header">
                         <h2>Claims</h2>
                     </div>
                     <div class="card-body">
                         <dl>
                             @foreach (var claim in user.Principal.Claims)
                             {
                                 <dt>@claim.Type</dt>
                                 <dd>@claim.Value</dd>
                             }
                         </dl>
                     </div>
                 </div>
             </div>
        
             <div class="col">
                 <div class="card">
                     <div class="card-header">
                         <h2>Properties</h2>
                     </div>
                     <div class="card-body">
                         <dl>
                             @foreach (var prop in user.Properties.Items)
                             {
                                 <dt>@prop.Key</dt>
                                 <dd>@prop.Value</dd>
                             }
                             @if (Model.Clients.Any())
                             {
                                 <dt>Clients</dt>
                                 <dd>
                                     @{
                                         var clients = Model.Clients.ToArray();
                                         for(var i = 0; i < clients.Length; i++)
                                         {
                                             <text>@clients[i]</text>
                                             if (i < clients.Length - 1)
                                             {
                                                 <text>, </text>
                                             }
                                         }
                                     }
                                 </dd>
                             }
                         </dl>
                     </div>
                 </div>
             </div>
         </div>
     </div>
 }



 